#!/bin/sh

cpu_arch="4*Cortex-A76 + 4*Cortex-A55"

cpu_freq="$(expr $(cat /sys/devices/system/cpu/cpufreq/policy0/cpuinfo_cur_freq) / 1000)MHz"

big0_cpu_freq="$(expr $(cat /sys/devices/system/cpu/cpufreq/policy4/cpuinfo_cur_freq) / 1000)MHz"

big1_cpu_freq="$(expr $(cat /sys/devices/system/cpu/cpufreq/policy6/cpuinfo_cur_freq) / 1000)MHz"

cpu_temp="$(awk "BEGIN{printf (\"%.1f\n\",$(cat /sys/class/thermal/thermal_zone0/temp)/1000) }")°C"

echo -n "${cpu_arch} ( ${cpu_freq} / ${big0_cpu_freq} / ${big1_cpu_freq} , ${cpu_temp} )"
